### ISSUE TITLE
How to install cdt-proc to eclipse .

### ISSUE THREAD

**Issue by nirangasandaruwan** [buntatsu/cdt-proc#1]
please explain me how to add this to eclipse.
thanks.

**Comment by buntatsu** [comment]
Sorry for the late reply.

Installation method is the following.

1. Install Eclipse CDT.
    http://www.eclipse.org/cdt/

2. Download the zip file from https://github.com/buntatsu/cdt-proc/releases.

3. Unzip the file.

4. Backup CDT core files in Eclipse plugin folder.
    For example,
      org.eclipse.cdt.core_5.9.1.201502131403.jar
      org.eclipse.cdt.core.source_5.9.1.201502131403.jar

5. Copy the unzipped files into Eclipse plugin folder.

Regards.

**Comment by nirangasandaruwan** [comment]
1.I downloaded Eclipse IDE for C/C++ Developers using below url
http://www.eclipse.org/downloads/packages/eclipse-ide-cc-developers/lunasr2

2.Install Eclipse CDT.to  Eclipse IDE for C/C++ Developer
http://www.eclipse.org/cdt/

and followed your other steps and it didnt worked for me

**Comment by nirangasandaruwan** [comment]
worked successfully

**Comment by nirangasandaruwan** [comment]
can you develop plugin for codeblock IDE
http://www.codeblocks.org/downloads
for pro c development.

**Comment by buntatsu** [comment]
Sorry, I can't develop plugin for Code::Blocks.
I don't use Code::Blocks.

**Comment by denis1008** [comment]
followed your other steps and it didnt worked for me
