### ISSUE TITLE
Did not work for Eclipse CDT 8.5 and plugin version v8.5.0-1.0

### ISSUE THREAD

**Issue by kuroburki** [buntatsu/cdt-proc#15]
I have followed the instructions to copy the rebuilt cdt cores and cdt jar to my eclipse plugins directory. I restarted Eclipse and verified the plugin is listed. However, I have a pro*C code project and there is no difference when I open the project. Eclipse still flags all the SQL syntax code as errors. Am I missing anything? Is there a version of your plugin tested with my version of Eclipse CDT?

My pro*C code is in files with extension .pc.

Eclipse version: Eclipse Luna SR 1a (4.4.1)
Oracle client: Oracle 11g (11.2.0.4)

![image](https://cloud.githubusercontent.com/assets/7956309/13079050/f55cccde-d487-11e5-878e-8d624577d0dd.png)

**Comment by buntatsu** [comment]
I will be able to access the net only on weekends. Please wait.

**Comment by kuroburki** [comment]
Thanks for looking into this.

**Comment by buntatsu** [comment]
There was no problem in my environment.
(luna-SR1a + cdt_8_5_pub-1.0.zip + cdt-proc-3.3.0.zip)

Please try to start eclipse with -clean and check Eclipse installation detail.

![detail](https://cloud.githubusercontent.com/assets/7479138/13184562/f8e146dc-d77f-11e5-9fac-b5d1ed5ac966.png)

**Comment by kuroburki** [comment]
I picked up CDT 3.0.0. Let me try with CDT 3.3.0 and get back to you.

**Comment by kuroburki** [comment]
I have the correct version installed now and the syntax errors are resolved. I get below warnings. Do you know if these are supported?

![image](https://cloud.githubusercontent.com/assets/7956309/13207494/eb70758a-d8d4-11e5-9708-061be0c6d377.png)

![image](https://cloud.githubusercontent.com/assets/7956309/13207497/f3f98ac0-d8d4-11e5-816d-220eb2f5be19.png)

![image](https://cloud.githubusercontent.com/assets/7956309/13207509/fc258b54-d8d4-11e5-80eb-dbd29f81e9f6.png)

**Comment by buntatsu** [comment]
They are supported.
However, the case of the keywords must be unified.
<img width="288" alt="luna-sr1" src="https://cloud.githubusercontent.com/assets/7479138/13338449/d3673684-dc64-11e5-8804-bc01e352c99b.png">
