### ISSUE TITLE
Unable to install plugin in Eclipse

### ISSUE THREAD

**Issue by alvydrenkov** [buntatsu/cdt-proc#18]
Hello.

I'm on Win 7 Corp SP1 64 bit.
I installed Eclipse IDE for C/C++ Developers - Mars.2 Release (4.5.2)
Then I installed "CDT 8.8.1 for Eclipse Mars" using Eclipse's "Help -> Install new software" menu item.
Then I downloaded cdt-proc-3.3.0.zip & cdt_8_8_1_pub-1.0.zip, unzipped them and copied 4 jars (buntatsun.cdt.proc.ui_3.3.0.jar, buntatsun.cdt.proc_3.3.0.jar, org.eclipse.cdt.core.source_5.11.0.201602051005.jar, org.eclipse.cdt.core_5.11.0.201602051005.jar) into ...\eclipse\dropins\cdt-proc directory.

After I restarted Eclipse, syntax in *.pc files is not highlighted. There's no cdt-proc mentioned in "Help -> Installation details -> Plug-ins".

Looks like I correctly followed your installation instructions and downloaded correct zips which are relevant to my Eclipse version.

Can you please recommend something to solve the problem?

**Comment by buntatsu** [comment]
Please copy the files that you unzipped to the directory where org.eclipse.cdt.core_5.11.0.201602051005.jar exists.
(overwrite org.eclipse.cdt.core_5.11.0.201602051005.jar)

**Comment by alvydrenkov** [comment]
I copied [buntatsun.cdt.proc.ui_3.3.0.jar, buntatsun.cdt.proc_3.3.0.jar, org.eclipse.cdt.core.source_5.11.0.201602051005.jar, org.eclipse.cdt.core_5.11.0.201602051005.jar] into D:\Users\vydrenkov\.p2\pool\plugins\, overwriting [org.eclipse.cdt.core.source_5.11.0.201602051005.jar, org.eclipse.cdt.core_5.11.0.201602051005.jar].

Nothing changed after I restarted Eclipse: syntax in *.pc files is not highlighted, no cdt-proc mentioned in "Help -> Installation details -> Plug-ins".

**Comment by buntatsu** [comment]
Have you tried "eclipse.exe -clean" ?

**Comment by alvydrenkov** [comment]
Just tried it, did not help to resove the issue

**Comment by buntatsu** [comment]
Please try to move buntatsun.cdt.proc.ui_3.3.0.jar and buntatsun.cdt.proc_3.3.0.jar in eclipse\dropins.

Subdirectory (cdt-proc) does not need.

**Comment by alvydrenkov** [comment]
That did it, now syntax is highlighted. Appreciate your help on this.

**Comment by buntatsu** [comment]
That's great. Enjoy!
