### ISSUE TITLE
Install but not working

### ISSUE THREAD

**Issue by idkang72** [buntatsu/cdt-proc#19]
Hi, I need you help.

I installed cdt-proc on eclipse 4.5.2 x64 using jre 1.8.91 in my Windows 10 PC.
But It's not woking. I can't see Pro*C preferences under C/C++ menu.

I downloaded "cdt-proc-3.3.0.zip" and "cdt_8_8_1_pub-1.0.zip" files,
backup original "org.eclipse.cdt.core_5.9.1.201502131403.jar" file,
and unzip files into plugins folder "{UserDir}/.p2/pool/plugins"

I confirmed followed files in the plugins folder.
- buntatsun.cdt.proc.ui_3.3.0.jar
- buntatsun.cdt.proc_3.3.0.jar
- org.eclipse.cdt.core_5.11.0.201602051005.jar
- org.eclipse.cdt.core.source_5.11.0.201602051005.jar

last, I started my eclipse but it's not working.
There was no error message in .metadata/.log about cdt and cdt-proc.

what should I do? Please help.

**Comment by buntatsu** [comment]
Please check https://github.com/buntatsu/cdt-proc/issues/18 .

**Comment by idkang72** [comment]
Wow! It works!

Thank you for you help and sorry that I didn't search other issues before asking.

How about updating install guide for new cdt-proc user.
I think that it is common problem when installing it.

Now I can edit Pro*C file with syntax coloring and ... in my eclipse! ^^
