### ISSUE TITLE
Compatibility with Color Themes

### ISSUE THREAD

**Issue by kuroburki** [buntatsu/cdt-proc#20]
I installed Eclipse Color Themes from the MarketPlace and switched to one of the available themes. Eclipse threw up errors for the cdt-proc plugin. Now I get the error even if I switch the default Eclipse color schemes. I have attached screenshot.

![image](https://cloud.githubusercontent.com/assets/7956309/16452564/c03b31f2-3dce-11e6-826e-1f6028b815ca.png)

Eclipse CDT: 8.8.1
Eclipse Color Themes: 1.0.0

**Comment by buntatsu** [comment]
The error does not occur in my environment.
cdt-proc's version Is 3.3.0 ?

**Comment by kuroburki** [comment]
Yes, my cdt-proc version is 3.3.0. I have switched back to default theme for now.

**Comment by buntatsu** [comment]
There is no error by changing theme in my environment.
Sorry, I do not know the cause of the error.
