### ISSUE TITLE
Declaration of loop variable used inside EXEC SQL block

### ISSUE THREAD

**Issue by chrisallen21** [buntatsu/cdt-proc#22]
EXEC SQL BEGIN DECLARE SECTION;
        int returnCode;
        varchar systemId[10 + 1];
        varchar relSystemId[10][10 + 1];
    EXEC SQL END DECLARE SECTION;

<some additional code removed>

        EXEC SQL EXECUTE
        BEGIN
            A_Stored_Procedure_Name
            (
                :systemId,
                :returnCode,
                :relSystemId,
            );

            FOR x IN 1 .. 2 LOOP
              **IF :relSystemId(x) IS NOT NULL THEN**
                  <additional code removed>
              END IF;
            END LOOP;

        END;
        END-EXEC;

I am receiving  "Symbol 'x' could not be resolved" error message on the IF condition. I do not believe that For Loop index variables need to be explicitly declared ahead of time (http://www.plsqltutorial.com/plsql-for-loop/).

If I define the 'x' variable in the EXEC SQL DECLARE block, the error message disappears.

**Comment by buntatsu** [comment]
Hi,
Sorry for too late reply.
I released 3.5.0.
Please try it.

**Comment by chrisallen21** [comment]
Issue has been resolved. Thanks!
