### ISSUE TITLE
Plugin not working with CDT 9.3.3

### ISSUE THREAD

**Issue by gdsotirov** [buntatsu/cdt-proc#28]
The plug in is not working with CD 9.3.3, which was released recently.

**Comment by jmramosr** [comment]
You can check all the versions in my repo:

https://github.com/jmramosr/Pro-C-for-Eclipse

All releases from 9.4.0 to 9.6.0

**Comment by gdsotirov** [comment]
Thanks for the info @jmramosr! I though the plugin of @buntatsu is going to be integrated into Eclipse, but it's good to see that the work is continued :-)

**Comment by gdsotirov** [comment]
No need for this one to remain open.
