### ISSUE TITLE
Syntax errors in DECLARE BEGIN END blocks

### ISSUE THREAD

**Issue by gdsotirov** [buntatsu/cdt-proc#4]
We have sources with DECLARE BEGIN END blocks, which are producing syntax errors (see screen shot with an example below).

![ecdt_proc_err_on_begin](https://cloud.githubusercontent.com/assets/955033/9608079/387100f8-50d5-11e5-8c46-aff1ca202259.png)

In real sources the editor is also trying to resolve the members of records, which is only possible into the database and thus produces "Filed could not be resolved" errors.

**Comment by gdsotirov** [comment]
I find no difference in release 2.0 and 2.1 and the errors still exist (see below). First one on BEGIN is "Missing ';'" and the rest are "Syntax error".

![ecdt_proc_warn_on_begin_in_2 1](https://cloud.githubusercontent.com/assets/955033/9927522/dba925c6-5d27-11e5-84ef-2db7a6945f84.png)

Here below is the test code I'm using:

```
EXEC SQL WHENEVER SQLERROR DO return(1);
EXEC SQL EXECUTE
           DECLARE
             obj PKG.type;
           BEGIN
             obj := NULL;
             obj.Filed1 := 'TEST';
             obj.Field2 := 'FOO';

             PKG.proc(obj);
           END;
         END-EXEC;
```

**Comment by buntatsu** [comment]
You must meet the C language syntax.

<img width="349" alt="ss" src="https://cloud.githubusercontent.com/assets/7479138/9935395/505605f6-5d91-11e5-9222-f5d1b637a8d7.png">

**Comment by gdsotirov** [comment]
Sure, the statement cannot be outside function body, but isn't the error starting on BEGIN somehow confusing? For example an error like "Statement not allowed here" on EXECUTE would be more clear and to the point.

**Comment by buntatsu** [comment]
When a syntax error occurred, cdt-proc ignored until the semicolon from "EXEC SQL". Therefore "BEGIN" became the first error.
For now, I updated parser to ignore until "END-EXEC".
It's a bit iffy.
