### ISSUE TITLE
Syntax coloring of the queries in Pro*C/C++ sources

### ISSUE THREAD

**Issue by gdsotirov** [buntatsu/cdt-proc#5]
It would be nice to have the SQL queries in Pro*C/C++ sources colored like in other editors. For example I would like to bold the keywords and have the built in Oracle functions colored in maroon, etc.

**Comment by buntatsu** [comment]
It's very difficult.
Please be patiently waiting.

**Comment by gdsotirov** [comment]
I would and of course please, let me know if I could help somehow.

**Comment by gdsotirov** [comment]
The syntax highlighting added in [release 3.2.0](https://github.com/buntatsu/cdt-proc/releases/tag/3.2.0) is nice (even restricted) and I'm now able to read Pro*C/C++ programs in Eclipse in the way I used to. Great thanks for implementing this! You rock!

**Comment by buntatsu** [comment]
I worked hard ;-)

**Comment by gdsotirov** [comment]
I'm not sure why this remained open, so close again.

**Comment by gdsotirov** [comment]
In fact, what remained is just to fix the syntax coloring of single line comments in SQL (see #3).
