### ISSUE TITLE
Are there any special requirements for installing in a Linux distribution of Eclipse CDT (kepler)?

### ISSUE THREAD

**Issue by markkoch** [buntatsu/cdt-proc#7]

**Comment by buntatsu** [comment]
Please install "for CDT8.3".
https://github.com/buntatsu/cdt-proc/releases/tag/v1.0.0

**Comment by markkoch** [comment]
Thanks for the reply,

Yes, that is the download I chose to install but I am seeing errors mainly on recognizing the EXEC keyword.

        EXEC SQL OPEN V3DetailCursor;

EXEC SQL statements all generate the error:     Statement has no effect `XEC`

Is this a problem with this older version, I didn`t see this problem in the version I installed on windows.

Mark

**Comment by buntatsu** [comment]
Hmm, do you tell me the version of cdt on the Linux ?

**Comment by markkoch** [comment]
Eclipse IDE for C/C++ Developers version 2.0.2.20140224-0000

Version: Kepler Service Release 2
Build id: 20140224-0627

CDT 8.3.0.201402142303

**Comment by buntatsu** [comment]
Version of your cdt is expected.
Sorry, I will not be able to investigate the cause of the error because I do not use a Linux.
Can you try Luna or Mars?

**Comment by markkoch** [comment]
OK.

No currently I cannot use Luna or Mars because the linux we are using is too old to run either of these.
